### ISSUE TITLE
Create Tech Stack Presentation

### ISSUE THREAD

**Issue by kenny5033** [Energy-Visualizer/eviz#1]
## Overview

Create a presentation for the technology stack to be used on this project. Possible technologies will be ranked using a decision matrix.

Example decision matrix (in Markdown) (and made up values)
|  | Panel | Django/HTMX |
|:---:|:---:|:---:|
| Longevity | 3 | 4 |
| Development Speed | 5 | 5 |

# Todo

- [ ] Create the rows of the decision matrix. What is important for our technologies to have?
- [ ] Create the columns of the decision matrix. What is technologies are we interested in exploring?
- [ ] Explore the listed technologies and evaluate them based on the rows.
- [ ] Keep notes about pros / cons of technologies.
- [ ] Put together presentation. Prezi? Google Slides?

**Comment by kenny5033** [comment]
- [] test

**Comment by kenny5033** [comment]
Presented today @ 10am to the Energy Economics Team
